version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017" # Expose MongoDB to host

  server:
    build: ./backend
    container_name: saja0217/cafe-r-backend:latest
    ports:
      - "5000:5000" # Key change: Map to same port internally/externally
    environment:
      - MONGO_URI=mongodb://mongo:27017/Cafe_R-db
    depends_on:
      - mongo

  client:
    build: ./frontend
    container_name: saja0217/cafe-r-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # Force development mode
      - REACT_APP_API_URL=http://localhost:5000 # Point to host's localhost
    depends_on:
      - server
